services:
  searxng:
    image: searxng/searxng:latest
    ports:
      - "11505:8080"
    volumes:
      - ./linux/searxng:/etc/searxng
    restart: always
  open-webui:
    image: ghcr.io/open-webui/open-webui@sha256:4dabf6994212b02e6651f129e39c513553016d519050ac951c195eccd3045cb9
    ports:
      - "11500:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=False
      - WEBUI_SESSION_COOKIE_SAME_SITE=None
      - WEBUI_SESSION_COOKIE_SECURE=True
      - ENABLE_RAG_WEB_SEARCH=True
      - ENABLE_EVALUATION_ARENA_MODELS=False
      - RAG_WEB_SEARCH_ENGINE=searxng
      - DEFAULT_MODELS=tinyllama
      - SEARXNG_QUERY_URL=http://host.docker.internal:11505
    restart: always

volumes:
  open-webui:
