services:
  rd-open-webui-ext:
    image: ${DESKTOP_PLUGIN_IMAGE}
  searxng:
    image: searxng/searxng:latest
    ports:
      - "11505:8080"
    volumes:
      - ./linux/searxng:/etc/searxng
    restart: always
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "11500:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=False
      - WEBUI_SESSION_COOKIE_SAME_SITE=None
      - WEBUI_SESSION_COOKIE_SECURE=True
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
            - DEFAULT_MODELS=tinyllama
      - SEARXNG_QUERY_URL=http://host.docker.internal:11505
    restart: always

volumes:
  open-webui:
